### ISSUE TITLE
Message not vertically centered

### ISSUE THREAD

**Issue by ryanbuening** [manumaticx/Toasti#11]
I have the height set to 10%, but I believe this happens regardless of what the height is set at. Running this in an iPhone Retina simulator.

![toast](https://f.cloud.github.com/assets/812974/2101124/c3ba0eb4-8f4f-11e3-9bfa-9636360f9178.png)

**Comment by manumaticx** [comment]
@rbuening28 thanks for the finding, let me know if 1.4.1 works for you

**Comment by ryanbuening** [comment]
That did work. Thanks! Widget looks and works great.

---

Ryan Buening
ryanbuening@gmail.com
